#!/bin/bash
#author : Christian Tchimi
#creation date : 09/02/2022
#last modified : 09/02/2022
#script description : This scrpit is for creating a s3 bucket and file then append file to bucket
echo
echo
echo " This script was design to create an S3 bucket and file then append file to the bucket "
echo
echo
sleep 3
read -p "Enter a bucket name : " bucket_name
sleep 2
echo
echo
if [[ ! -z $(aws s3api list-buckets --query 'Buckets[?Name=='bucket_name']' --output text) ]];
 then echo "This bucket is already exist "
else  
echo "We are  creating the bucket $bucket_name "
echo
sleep 3
echo
aws s3 mb s3://$bucket_name
echo
echo
sleep 2
echo
read -p "Enter a file name to create in the bucket : " file_name
echo
echo " we are creating the file  $file_name  "
echo
touch $file_name
echo
sleep 3
echo " $file_name was created "
sleep 3
echo "Now  we are adding $file_name to the bucket $bucket_name "
echo 
aws s3 cp $file_name s3://$bucket_name/
sleep 2
aws s3 ls
fi
